/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectArchiveRouteImport } from './routes/project/archive'
import { Route as ProjectNameRouteImport } from './routes/project/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectArchiveRoute = ProjectArchiveRouteImport.update({
  id: '/project/archive',
  path: '/project/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$name': typeof ProjectNameRoute
  '/project/archive': typeof ProjectArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$name': typeof ProjectNameRoute
  '/project/archive': typeof ProjectArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$name': typeof ProjectNameRoute
  '/project/archive': typeof ProjectArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project/$name' | '/project/archive'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$name' | '/project/archive'
  id: '__root__' | '/' | '/project/$name' | '/project/archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectNameRoute: typeof ProjectNameRoute
  ProjectArchiveRoute: typeof ProjectArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/archive': {
      id: '/project/archive'
      path: '/project/archive'
      fullPath: '/project/archive'
      preLoaderRoute: typeof ProjectArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectNameRoute: ProjectNameRoute,
  ProjectArchiveRoute: ProjectArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
